import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import "@/styles/globals.scss";
import AppContextProvider from "@/contexts/providers/AppContextProvider";

const quicksand = Quicksand({
  variable: "--font-quicksand",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Authorization Project",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${quicksand.variable} antialiased`}>
        <AppContextProvider>{children}</AppContextProvider>
      </body>
    </html>
  );
}
